---
# Jupyter LLM docker compose by Matthew Printz

version: '3'

networks:
  beaker-net:
    driver: bridge

services:
  jupyter:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8888:8888"
    environment:
      - DEBUG=1
      - JUPYTER_SERVER=http://jupyter:8888
      - JUPYTER_TOKEN=89f73481102c46c0bc13b2998f9a4fce
      - ENABLE_USER_PROMPT=true
      - OPENAI_API_KEY
    volumes:
       # - ./beaker_kernel:/usr/local/share/jupyter/kernels/beaker_kernel
      # - ./beaker_kernel:/usr/local/share/jupyter/kernels/beaker_kernel
      # - .:/jupyter
      - .:/bio_context
    command:
      [
        "python",
        "-m",
        "beaker_kernel.server.dev",
        "--ip",
        "0.0.0.0",
        "-y",
        "watch"
      ]
    networks:
      - beaker-net

  chromadb:
    image: chromadb/chroma:latest
    environment:
      - IS_PERSISTENT=TRUE
    volumes:
      - /media/hdd/Code/beaker-bio/chromabd_functions:/chroma/chroma/
    ports:
      - 8000:8000
    networks:
      - beaker-net

# volumes:
#   chroma-data:
#     driver: local
